### ISSUE TITLE
The website biomatic-ui.com is down

### ISSUE THREAD

**Issue by gabrielizalo** [BioMaRu/biomatic#18]
Hello ...
The website: https://biomatic-ui.com/ is getting a **Site Not Found** in **Firebase**.

**Comment by BioMaRu** [comment]
Oh! Thank you.
I will fix this problem real quick; please use https://biomatic-doc.firebaseapp.com/ in the meantime.

**Comment by BioMaRu** [comment]
Domain biomatic-ui.com should be propagating now and will come back in 1-2 hour
